development:
  clients:
    default:
      database: <%= ENV['MONGO_DB'] || 'order_service' %>
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost' %>:<%= ENV['MONGO_PORT'] || 27017 %>
      options:
        user: <%= ENV['MONGO_USER'] || 'root' %>
        password: <%= ENV['MONGO_PASSWORD'] || 'root123' %>
        auth_source: admin

test:
  clients:
    default:
      database: <%= ENV['MONGO_DB_TEST'] || 'order_service_test' %>
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost' %>:<%= ENV['MONGO_PORT'] || 27017 %>
      options:
        user: <%= ENV['MONGO_USER'] || 'root' %>
        password: <%= ENV['MONGO_PASSWORD'] || 'root123' %>
        auth_source: admin
